import os
import sys
import json
import datetime
import warnings
import pandas as pd
from tqdm import tqdm
from pathlib import Path
from mdutils.mdutils import MdUtils

# Suppress warnings
warnings.filterwarnings("ignore", module="statsmodels")
warnings.filterwarnings("ignore", message="Tight layout not applied")
pd.options.mode.chained_assignment = None


sys.path.append(str(Path(__file__).parent))
import operation_types
from data import process_gas_bench_data
from runtime_estimation import (
    estimate_run_time_for_simple_operation,
    estimate_run_time_for_non_simple_operation,
)


MEMORY_PARAMS = [
    "calldata_size",
    "mem_size",
    "code_size",
    "msg_size",
    "copy_size",
    "return_size",
]

LOG_PARAMS = [
    "log_size",
    "mem_size",
]

PRECOMPILE_PARAMS = [
    "size",
    "num_rounds",
    "k",
    "num_pairs",
]


### Simple opcode analysis ################################################################


def generate_simple_opcode_report(gas_bench_df: pd.DataFrame, out_dir: str) -> None:
    # Start markdown report
    md_file = MdUtils(
        file_name=os.path.join(out_dir, "simple_opcode_autogenerated_report"),
        title=f"Opcode run times estimation results - Simple opcodes",
    )
    md_file.new_header(level=1, title="Introduction", add_table_of_contents="n")
    md_file.new_paragraph(
        f"""
This is an automated report generated from the opcode run times 
estimation script `./src/estimate_opcode_run_times.py`. The script 
uses data generated by running the 
[EEST benchmark suite](https://github.com/ethereum/execution-spec-tests/tree/main/tests/benchmark) 
with the [Nethermind benchmarking tooling](https://github.com/NethermindEth/gas-benchmarks).

The data includes all the simple opcode tests run between {start_date} and {run_time.strftime('%Y-%m-%d')}.

For each opcode and client, an NNLS linear regression model is fitted to estimate the 
opcode run time as a function of the opcode count. The results are presented below.
"""
    )
    # Estimate run times for simple opcodes (i.e. no inputs or params)
    out_list = []
    simple_opcodes = operation_types.SIMPLE_COMPUTE
    for opcode in tqdm(simple_opcodes, desc="Estimating simple opcodes"):
        # Run estimation and add to report
        opcode_list = estimate_run_time_for_simple_operation(
            gas_bench_df, opcode, md_file, out_dir
        )
        out_list.extend(opcode_list)
    # Create and save output dataframe
    out_df = pd.DataFrame(out_list)
    out_df.to_csv(os.path.join(out_dir, "simple_opcodes_results.csv"), index=False)
    # Finish and save markdown file
    md_file.new_table_of_contents(depth=1)
    md_file.create_md_file()


### Non-simple opcode analysis ################################################################


def generate_non_simple_opcode_report(
    gas_bench_df: pd.DataFrame, out_dir: str, op_type: str
) -> None:
    # Start markdown report
    md_file = MdUtils(
        file_name=os.path.join(out_dir, f"{op_type}_opcode_autogenerated_report"),
        title=f"Opcode run times estimation results - {op_type} opcodes",
    )
    md_file.new_header(level=1, title="Introduction", add_table_of_contents="n")
    md_file.new_paragraph(
        f"""
This is an automated report generated from the opcode run times 
estimation script `./src/estimate_opcode_run_times.py`. The script 
uses data generated by running the 
[EEST benchmark suite](https://github.com/ethereum/execution-spec-tests/tree/main/tests/benchmark) 
with the [Nethermind benchmarking tooling](https://github.com/NethermindEth/gas-benchmarks).

The data includes all the {op_type} opcode tests run between {start_date} and {run_time.strftime('%Y-%m-%d')}.

For each opcode and client, an NNLS linear regression model is fitted to estimate the 
opcode run time as a function of the opcode count and other opcode configurations. The results are presented below.
"""
    )
    # Process op_type
    if op_type == "memory":
        opcodes = operation_types.MEMORY_COMPUTE
        params = MEMORY_PARAMS
    elif op_type == "log":
        opcodes = operation_types.LOG
        params = LOG_PARAMS
    else:
        raise ValueError("op_type must be `memory` or `log`")

    # Estimate run times for variable opcodes (i.e. with inputs or params)
    out_list = []
    for opcode in tqdm(opcodes, desc=f"Estimating {op_type} opcodes"):
        # Run estimation and add to report
        opcode_list = estimate_run_time_for_non_simple_operation(
            gas_bench_df, opcode, md_file, out_dir, params
        )
        out_list.extend(opcode_list)
    # Create and save output dataframe
    out_df = pd.DataFrame(out_list)
    out_df.to_csv(os.path.join(out_dir, f"{op_type}_opcodes_results.csv"), index=False)
    # Finish and save markdown file
    md_file.new_table_of_contents(depth=1)
    md_file.create_md_file()


### Precompiles analysis ##################################################################


def generate_precompiles_report(gas_bench_df: pd.DataFrame, out_dir: str) -> None:
    # Start markdown report
    md_file = MdUtils(
        file_name=os.path.join(out_dir, f"precompiles_autogenerated_report"),
        title="Opcode run times estimation results - Precompiles",
    )
    md_file.new_header(level=1, title="Introduction", add_table_of_contents="n")
    md_file.new_paragraph(
        f"""
This is an automated report generated from the opcode run times 
estimation script `./src/estimate_opcode_run_times.py`. The script 
uses data generated by running the 
[EEST benchmark suite](https://github.com/ethereum/execution-spec-tests/tree/main/tests/benchmark) 
with the [Nethermind benchmarking tooling](https://github.com/NethermindEth/gas-benchmarks).

The data includes all the precompile tests run between {start_date} and {run_time.strftime('%Y-%m-%d')}.

For each opcode and client, an NNLS linear regression model is fitted to estimate the 
precompile run time as a function of the precompile count and other configurations. The results are presented below.

Everytime the report references "opcode", assume we it means "precompile". 
"""
    )
    # Estimate run times for simple precompiles
    out_list = []
    for precomp in tqdm(
        operation_types.SIMPLE_PRECOMPILES, desc=f"Estimating simple precompiles"
    ):
        # Run estimation and add to report
        opcode_list = estimate_run_time_for_simple_operation(
            gas_bench_df, precomp, md_file, out_dir
        )
        out_list.extend(opcode_list)
    # Estimate run times for complex precompiles
    for precomp in tqdm(
        operation_types.VARIABLE_PRECOMPILES, desc=f"Estimating variable precompiles"
    ):
        # Run estimation and add to report
        opcode_list = estimate_run_time_for_non_simple_operation(
            gas_bench_df, precomp, md_file, out_dir, PRECOMPILE_PARAMS
        )
        out_list.extend(opcode_list)
    # Create and save output dataframe
    out_df = pd.DataFrame(out_list)
    out_df.to_csv(os.path.join(out_dir, "precompiles_results.csv"), index=False)
    # Finish and save markdown file
    md_file.new_table_of_contents(depth=1)
    md_file.create_md_file()


### Main runner ###########################################################################


if __name__ == "__main__":
    run_time = datetime.datetime.now()
    # Start date for querying
    start_date = "2026-01-15"
    # Directories
    file_dir = os.path.dirname(os.path.abspath(__file__))
    repo_dir = os.path.abspath(os.path.join(file_dir, ".."))
    out_dir = os.path.join(
        repo_dir,
        "reports",
        "opcode_run_times_estimation",
        f"{start_date}_{run_time.strftime('%Y-%m-%d')}",
    )
    os.makedirs(out_dir, exist_ok=True)
    os.makedirs(os.path.join(out_dir, "figs"), exist_ok=True)
    # Secrets for acessing gas bench DB
    with open(os.path.join(repo_dir, "secrets.json"), "r") as file:
        secrets_dict = json.load(file)
    user = secrets_dict["gas_bench_username"]
    password = secrets_dict["gas_bench_password"]
    # Query raw data and save
    compute_gas_bench_df, _ = process_gas_bench_data(
        user, password, start_date, "compute_perf_devnet_2"
    )
    state_gas_bench_df, _ = process_gas_bench_data(
        user, password, start_date, "stateful_perf_devnet_2"
    )
    gas_bench_df = pd.concat(
        [compute_gas_bench_df, state_gas_bench_df], ignore_index=True
    )
    outfile = os.path.join(out_dir, "gas_bench_data.csv")
    gas_bench_df.to_csv(outfile, index=False)
    # Run estimations and generate reports
    generate_simple_opcode_report(gas_bench_df, out_dir)
    generate_non_simple_opcode_report(gas_bench_df, out_dir, "memory")
    generate_non_simple_opcode_report(gas_bench_df, out_dir, "log")
    generate_precompiles_report(gas_bench_df, out_dir)
