import os
import sys
import json
import datetime
import warnings
import pandas as pd
from tqdm import tqdm
from pathlib import Path
from mdutils.mdutils import MdUtils

# Suppress warnings
warnings.filterwarnings("ignore", module="statsmodels")
warnings.filterwarnings("ignore", message="Tight layout not applied")
pd.options.mode.chained_assignment = None


sys.path.append(str(Path(__file__).parent))
import operation_types
from estimate_opcode_run_times import (
    process_gas_bench_data,
    estimate_run_time_for_non_simple_operation,
    estimate_run_time_for_simple_operation,
)


PARAMS = [
    "num_rounds",
    "num_pairs",
    "msg_size",
    "mem_size",
]


def generate_runtime_report(
    gas_bench_df: pd.DataFrame,
    out_dir: str,
) -> None:
    # Start markdown report
    md_file = MdUtils(
        file_name=os.path.join(out_dir, f"runtime_estimation_autogenerated_report"),
        title=f"Operation run times estimation results - EIP-7904",
    )
    md_file.new_header(level=1, title="Introduction", add_table_of_contents="n")
    md_file.new_paragraph(
        f"""
This is an automated report generated from the opcode run times 
estimation script `./src/estimate_opcode_run_times.py`. The script 
uses data generated by running the 
[EEST benchmark suite](https://github.com/ethereum/execution-spec-tests/tree/main/tests/benchmark) 
with the [Nethermind benchmarking tooling](https://github.com/NethermindEth/gas-benchmarks).

The data includes all the tests for operations repriced in EIP-7904 run between {start_date} and {run_time.strftime('%Y-%m-%d')}.

For each opcode and client, an OLS linear regression model is fitted to estimate the 
opcode run time as a function of the opcode count and other opcode configurations. The results are presented below.
"""
    )
    # Estimate run times for simple operations
    out_list = []
    for op in tqdm(
        operation_types.SIMPLE_EIP_7904, desc=f"Estimating simple operations"
    ):
        # Run estimation and add to report
        op_list = estimate_run_time_for_simple_operation(
            gas_bench_df, op, md_file, out_dir
        )
        out_list.extend(op_list)
    # Estimate run times for variable operations
    for op in tqdm(
        operation_types.VARIABLE_EIP_7904, desc=f"Estimating variable operations"
    ):
        # Run estimation and add to report
        opcode_list = estimate_run_time_for_non_simple_operation(
            gas_bench_df, op, md_file, out_dir, PARAMS
        )
        out_list.extend(opcode_list)
    # Create and save output dataframe
    out_df = pd.DataFrame(out_list)
    out_df.to_csv(os.path.join(out_dir, f"results.csv"), index=False)
    # Finish and save markdown file
    md_file.new_table_of_contents(depth=1)
    md_file.create_md_file()


if __name__ == "__main__":
    run_time = datetime.datetime.now()
    # Start date for querying
    start_date = "2026-01-10"
    # Directories
    file_dir = os.path.dirname(os.path.abspath(__file__))
    repo_dir = os.path.abspath(os.path.join(file_dir, ".."))
    out_dir = os.path.join(
        repo_dir,
        "reports",
        "eip-7904",
        "runtime_estimation",
        f"{start_date}_{run_time.strftime('%Y-%m-%d')}",
    )
    os.makedirs(out_dir, exist_ok=True)
    os.makedirs(os.path.join(out_dir, "figs"), exist_ok=True)
    # Secrets for acessing gas bench DB
    with open(os.path.join(repo_dir, "secrets.json"), "r") as file:
        secrets_dict = json.load(file)
    user = secrets_dict["gas_bench_username"]
    password = secrets_dict["gas_bench_password"]
    # Query raw data and save
    gas_bench_df = process_gas_bench_data(user, password, start_date)
    outfile = os.path.join(out_dir, "gas_bench_data.csv")
    gas_bench_df.to_csv(outfile, index=False)
    # Run estimations and generate reports
    generate_runtime_report(gas_bench_df, out_dir)
