import os
import sys
import pandas as pd
from pathlib import Path
from typing import Dict, List
from mdutils.mdutils import MdUtils

sys.path.append(str(Path(__file__).parent))
from runtime_estimation import estimate_run_time_for_glue_opcodes


def compute_glue_adjustment(
    glue_results_df: pd.DataFrame,
    glue_opcodes_by_test: pd.DataFrame,
) -> pd.DataFrame:
    """Compute glue opcode runtime adjustment for each test.

    For each (test_name, opcode, client), computes the total glue opcode
    runtime to subtract from the slope. This accounts for the fact that glue
    opcodes (e.g., PUSH1, CALL) scale with the main opcode count and their
    runtime is captured in the slope coefficient.

    The adjustment is: sum(ratio_i * glue_runtime_i) for all glue opcodes i
    where ratio_i is the average number of glue opcode instances per main opcode
    instance (averaged across test_params), and glue_runtime_i is the estimated
    per-execution runtime of the glue opcode for the given client. Only glue
    opcodes with a statistically significant fit (p_value < 0.05) are included.

    Returns:
        DataFrame with columns: test_name, opcode, client_name, glue_adjustment
    """
    # Average ratios across test_params for each (test_name, test_opcode, glue_opcode)
    avg_ratios = (
        glue_opcodes_by_test.groupby(["test_name", "test_opcode", "glue_opcode"])[
            "ratio"
        ]
        .mean()
        .reset_index()
    )
    # Only use glue opcodes with a statistically significant fit
    significant_glue = glue_results_df[glue_results_df["p_value"] < 0.05]
    # Merge with glue runtimes to get ratio * runtime per (test, opcode, glue_opcode, client)
    glue_with_runtime = avg_ratios.merge(
        significant_glue[["client", "glue_opcode", "runtime"]],
        on="glue_opcode",
        how="inner",
    )
    glue_with_runtime["glue_runtime_contribution"] = (
        glue_with_runtime["ratio"] * glue_with_runtime["runtime"]
    )
    # Sum contributions per (test_name, test_opcode, client)
    glue_adjustment = (
        glue_with_runtime.groupby(["test_name", "test_opcode", "client"])[
            "glue_runtime_contribution"
        ]
        .sum()
        .reset_index()
    )
    glue_adjustment = glue_adjustment.rename(
        columns={
            "test_opcode": "opcode",
            "client": "client_name",
            "glue_runtime_contribution": "glue_adjustment",
        }
    )
    return glue_adjustment


def get_glue_opcodes_by_test(
    trace_df: pd.DataFrame,
    eps: float = 0.05,
) -> Dict[str, Dict[str, float]]:
    # Define columns lists
    grouping_cols = [
        "test_file",
        "test_name",
        "test_opcode",
        "test_params",
    ]
    opcode_cols = trace_df.drop(
        columns=grouping_cols + ["test_title", "opcount", "block_limit_million"]
    ).columns.tolist()
    # filter tests with less than 5 runs (pearson correlation is not reliable)
    filtered_trace_df = trace_df.groupby(grouping_cols).filter(lambda g: len(g) > 5)
    # Compute correlation by group
    grouped = filtered_trace_df.groupby(grouping_cols)
    corrs = grouped.apply(
        lambda g: g[opcode_cols].corrwith(g["opcount"]),
        include_groups=False,
    )
    # Compute ratios by group
    ratios = grouped.apply(
        lambda g: g[opcode_cols].diff().mean() / g["opcount"].diff().mean(),
        include_groups=False,
    )
    # Add data to single dataframe + filter
    result_df = pd.DataFrame(
        {"corr": corrs.stack(), "ratio": ratios.stack()}
    ).reset_index()
    result_df = result_df.rename(columns={"level_4": "glue_opcode"})
    # Filter low correlations, self-correlations and low ratios
    result_df = result_df[
        result_df["corr"].notna()
        & (result_df["corr"] >= 1 - eps)
        & (result_df["ratio"] >= 0.0005)
        & (result_df["test_opcode"] != result_df["glue_opcode"])
    ]
    return result_df


def get_all_glue_opcodes_for_target_opcodes(
    target_opcodes: List[str], glue_opcodes_by_test: pd.DataFrame, max_iter: int = 1e5
):
    df = glue_opcodes_by_test[glue_opcodes_by_test["test_opcode"].isin(target_opcodes)]
    prev_glue_opcodes = []
    glue_opcodes = df["glue_opcode"].unique()
    i = 0
    while len(prev_glue_opcodes) != len(glue_opcodes) and i < max_iter:
        new_glue_opcodes = df[df["test_opcode"].isin(glue_opcodes)][
            "glue_opcode"
        ].unique()
        prev_glue_opcodes = glue_opcodes
        glue_opcodes = list(set(glue_opcodes).union(set(new_glue_opcodes)))
        i += 1
    return glue_opcodes


def generate_glue_opcode_report(
    start_date: str,
    end_date: str,
    eip_number: int,
    gas_bench_df: pd.DataFrame,
    trace_df: pd.DataFrame,
    out_dir: str,
    target_opcodes: List[str],
) -> None:
    print("Estimating glue operations...")
    # Start markdown report
    md_file = MdUtils(
        file_name=os.path.join(out_dir, f"glue_opcodes_autogenerated_report"),
        title=f"Operation run times estimation results - Glue opcodes",
    )
    md_file.new_header(level=1, title="Introduction", add_table_of_contents="n")
    md_file.new_paragraph(
        f"""
This is an automated report generated from the opcode run times
estimation script `./src/glue.py`. The script
uses data generated by running the
[EEST benchmark suite](https://github.com/ethereum/execution-spec-tests/tree/main/tests/benchmark)
with the [Nethermind benchmarking tooling](https://github.com/NethermindEth/gas-benchmarks).

The data includes all the tests for glue operations repriced in EIP-{eip_number} run
between {start_date} and {end_date}.

For each operation and client, an NNLS linear regression model is fitted to estimate the
operation run time as a function of the operation count.
The results are presented below.
"""
    )

    md_file.new_header(
        level=1, title="How to Interpret the Results", add_table_of_contents="n"
    )

    md_file.new_header(level=2, title="Model Used", add_table_of_contents="n")
    md_file.new_paragraph(
        """
**Non-Negative Least Squares (NNLS) Linear Regression** is used to estimate glue operation runtimes.
This model ensures all coefficients are non-negative, which is physically meaningful since
execution time cannot be negative.

Unlike the per-opcode models used for target operations, glue opcodes are estimated using a
**single model per client** that fits all glue opcode counts as features simultaneously. This means
the model estimates the runtime coefficients of all glue opcodes at the same time by solving:

`runtime = intercept + coef_1 × opcode_1_count + coef_2 × opcode_2_count + ... + coef_n × opcode_n_count`

where each `coef_i` represents the estimated per-execution runtime of the corresponding glue opcode.
This joint estimation approach accounts for correlations between glue opcode counts across tests,
producing more accurate estimates than fitting each glue opcode independently.

Only warm CALL variants are included in the model (cold CALL tests are excluded).
"""
    )

    md_file.new_header(
        level=2, title="Model Quality Metrics", add_table_of_contents="n"
    )
    md_file.new_paragraph(
        """
Each model reports two key metrics to assess the quality of the fit:

**R² (R-squared / Coefficient of Determination)**
- Ranges from 0 to 1 (or can be negative for very poor fits)
- Measures how well the model explains the variance in the data
- **Interpretation**:
  - R² > 0.9: Excellent fit - the model explains >90% of the variance
  - R² > 0.7: Good fit - the model captures most of the relationship
  - R² > 0.5: Acceptable fit - the model has predictive power but notable variance remains
  - R² < 0.5: Poor fit - the model may not be reliable

**p-value**
- Tests the statistical significance of each coefficient, based on a bootstrap sample estimation
- **Interpretation**:
  - p < 0.05: Statistically significant - the parameter has a real effect on runtime
  - p ≥ 0.05: Not significant - the parameter's effect cannot be distinguished from random noise

We also plot some diagnostic graphs for each operation and client combination to visually assess the model fit.
"""
    )
    # Get list of glue opcodes
    glue_opcodes_by_test = get_glue_opcodes_by_test(trace_df)
    glue_opcodes_by_test.to_csv(os.path.join(out_dir, f"glue_opcodes_by_test.csv"), index=False)
    glue_opcodes = get_all_glue_opcodes_for_target_opcodes(
        target_opcodes, glue_opcodes_by_test
    )
    # get opcode counts for all glue opcodes
    glue_df = trace_df[trace_df["test_opcode"].isin(glue_opcodes)][
        ["test_title"] + glue_opcodes
    ].fillna(0.0)
    glue_df = gas_bench_df[
        ["test_title", "client_name", "test_params", "run_duration_ms"]
    ].merge(glue_df, on="test_title", how="inner")
    # Estimate runtime for all opcodes together
    out_list = estimate_run_time_for_glue_opcodes(
        glue_df, glue_opcodes, out_dir, md_file
    )
    # Create and save output dataframe
    out_df = pd.DataFrame(out_list)
    out_df.to_csv(os.path.join(out_dir, f"glue_results.csv"), index=False)
    # Finish and save markdown file
    md_file.new_table_of_contents(depth=1)
    md_file.create_md_file()
