import os
import sys
import warnings
import numpy as np
import pandas as pd
from tqdm import tqdm
from typing import Dict, List, Set
from pathlib import Path
from mdutils.mdutils import MdUtils

# Suppress warnings
warnings.filterwarnings("ignore", module="statsmodels")
warnings.filterwarnings("ignore", message="Tight layout not applied")
pd.options.mode.chained_assignment = None


sys.path.append(str(Path(__file__).parent))
from plotting import create_and_save_new_gas_plot, create_and_save_state_access_gas_plot
from runtime_estimation import estimate_run_time_for_operation
from proposal import (
    select_worst_case_estimates,
    compute_worst_gas_proposal,
    find_missing_client_estimations,
    find_poor_fit_glue_opcodes,
    compute_state_access_gas_params,
    _STATE_ACCESS_CURRENT_GAS,
    _STATE_ACCESS_PARAM_SOURCES,
)


def generate_runtime_report(
    start_date: str,
    end_date: str,
    eip_number: int,
    gas_bench_df: pd.DataFrame,
    out_dir: str,
    params: List[str] = [],
    operations: List[str] = [],
    query_source: str = "gas_bench",
    group_by: List[str] = ["client_name", "test_name"],
) -> None:
    # Start markdown report
    md_file = MdUtils(
        file_name=os.path.join(out_dir, f"runtime_estimation_autogenerated_report"),
        title=f"Operation run times estimation results - EIP-{eip_number}",
    )
    md_file.new_header(level=1, title="Introduction", add_table_of_contents="n")
    if query_source == "gas_bench":
        md_file.new_paragraph(
            f"""
This is an automated report generated from the opcode run times
estimation script `./src/estimate_{eip_number}_repricings.py`. The script
uses data generated by running the
[EEST benchmark suite](https://github.com/ethereum/execution-spec-tests/tree/main/tests/benchmark)
with the [Nethermind benchmarking tooling](https://github.com/NethermindEth/gas-benchmarks).
"""
        )
    else:  # benchmarkoor
        md_file.new_paragraph(
            f"""
This is an automated report generated from the opcode run times
estimation script `./src/estimate_{eip_number}_repricings.py`. The script
uses data generated by running the
[EEST benchmark suite](https://github.com/ethereum/execution-spec-tests/tree/main/tests/benchmark)
with the [Benchmarkoor](https://github.com/ethpandaops/benchmarkoor) tool from EthPandasOps.
"""
        )
    md_file.new_paragraph(
        f"""
The data includes all the tests for operations repriced in EIP-{eip_number} run
between {start_date} and {end_date}.

For each operation and client, an NNLS linear regression model is fitted to estimate the
operation run time as a function of the operation count and other operation-specific parameters.
The results are presented below.
"""
    )
    md_file.new_header(
        level=1, title="How to Interpret the Results", add_table_of_contents="n"
    )

    md_file.new_header(level=2, title="Model Used", add_table_of_contents="n")
    md_file.new_paragraph(
        """
**Non-Negative Least Squares (NNLS) Linear Regression** is used to estimate operation runtimes.
This model ensures all coefficients are non-negative, which is physically meaningful since
execution time cannot be negative. The model estimates runtime as a linear combination of:

- **Constant term (intercept)**: Base overhead for executing the test, which includes setup and teardown time
- **Operation count (slope)**: Number of times the operation is executed in the test. This paramater 
is the one that allows us to estimate the per-operation runtime.
- **Operation-specific parameters**: Variables like number of rounds, message size, or number of pairs

For simple operations, the model estimates: `runtime = intercept + slope × operation_count`

For variable operations, the model estimates: `runtime = intercept + slope × operation_count +
 param1_coef × operation_count × param1 + param2_coef × operation_count × param2 + ...`
"""
    )

    md_file.new_header(
        level=2, title="Model Quality Metrics", add_table_of_contents="n"
    )
    md_file.new_paragraph(
        """
Each model reports two key metrics to assess the quality of the fit:

**R² (R-squared / Coefficient of Determination)**
- Ranges from 0 to 1 (or can be negative for very poor fits)
- Measures how well the model explains the variance in the data
- **Interpretation**:
  - R² > 0.9: Excellent fit - the model explains >90% of the variance
  - R² > 0.7: Good fit - the model captures most of the relationship
  - R² > 0.5: Acceptable fit - the model has predictive power but notable variance remains
  - R² < 0.5: Poor fit - the model may not be reliable

**p-value**
- Tests the statistical significance of each coefficient, based on a bootstrap sample estimation
- **Interpretation**:
  - p < 0.05: Statistically significant - the parameter has a real effect on runtime
  - p ≥ 0.05: Not significant - the parameter's effect cannot be distinguished from random noise

We also plot some diagnostic graphs for each operation and client combination to visually assess the model fit.
"""
    )

    # Estimate run times for simple operations
    out_list = []
    for op in tqdm(operations, desc=f"Estimating operations"):
        # Run estimation and add to report
        op_list = estimate_run_time_for_operation(
            gas_bench_df, op, md_file, out_dir, params, group_by=group_by
        )
        out_list.extend(op_list)
    # Create and save output dataframe
    out_df = pd.DataFrame(out_list)
    out_df.to_csv(os.path.join(out_dir, f"results.csv"), index=False)
    # Finish and save markdown file
    md_file.new_table_of_contents(depth=1)
    md_file.create_md_file()


def generate_repricings_report(
    start_date: str,
    end_date: str,
    out_dir: str,
    anchor_rate: float,
    eip_number: int,
    params: List[str],
    target_operations: List[str],
    params_multipliers: Dict[str, float] = dict(),
    group_by: List[str] = ["client_name", "test_name"],
) -> None:
    # Start markdown report
    md_file = MdUtils(
        file_name=os.path.join(out_dir, f"new_gas_proposal"),
        title=f"New gas cost proposal for EIP-{eip_number}",
    )
    md_file.new_paragraph(
        f"""
This is an automated report generated from the script `./src/estimate_{eip_number}_repricings.py`. 
The script uses the runtime estimation output generated by this script. 
The report with the runtime estimation results can be found in 
`./reports/eip-{eip_number}/{start_date}_{end_date}/runtime_estimation_autogenerated_report.md`.
"""
    )
    md_file.new_header(level=2, title="Methodology", add_table_of_contents="n")
    md_file.new_paragraph(
        f"""
New gas costs are calculated using an anchor rate of **{anchor_rate / 1e6:.0f} million gas per second**,
which represents a target execution rate for EVM operations. The formula used is:

```
new_gas = (anchor_rate * runtime_ms) / 1000
```

Where `runtime_ms` is the estimated runtime in milliseconds from the regression models.

**Glue opcode adjustment:** Each benchmark test includes auxiliary "glue" opcodes (e.g., PUSH, CALL)
that scale linearly with the main opcode count. Because the regression model's slope coefficient
captures the combined runtime of both the target opcode and its glue opcodes, we subtract the
estimated glue opcode runtime to isolate the true per-execution cost of the target opcode:

```
adjusted_slope = slope - sum(ratio_i * glue_runtime_i)
```

Where `ratio_i` is the average number of executions of glue opcode *i* per execution of the target
opcode (averaged across test parameters), and `glue_runtime_i` is the estimated per-execution runtime
of glue opcode *i* for the given client. Only glue opcodes with a statistically significant fit
(p-value < 0.05) are included in the adjustment. The adjusted slope is clipped to a minimum of zero.
Glue opcode runtimes are estimated separately using the same NNLS regression approach (see the
[glue opcodes report](./glue_opcodes_autogenerated_report.md) for details).
"""
    )
    md_file.new_header(
        level=2, title="Understanding the results", add_table_of_contents="n"
    )
    md_file.new_paragraph(
        """
The table below shows the **worst-case** gas costs across all tested clients (taking the maximum
estimated cost per operation). This conservative approach ensures that the new gas costs account
for the slowest implementation among the major Ethereum clients.

The **Change** column shows the relative change as a decimal (e.g., 1.0 = 100% increase, 0.5 = 50% increase,
-0.25 = 25% decrease). Operations with `inf` indicate costs going from 0 to a positive value.

For each operation, parameter, and client combination, the worst-case runtime across all
test configurations is selected. If any configuration has a statistically significant fit
(p-value < 0.05), the worst case among significant fits is used. Otherwise, the worst case
from all configurations is used. Operations with no significant fits are listed separately
in the "Errors and caveats" section.
"""
    )
    # Load estimation results and compute new gas costs
    results_df = pd.read_csv(os.path.join(out_dir, f"results.csv"))
    glue_results_df = pd.read_csv(os.path.join(out_dir, f"glue_results.csv"))
    glue_opcodes_by_test = pd.read_csv(
        os.path.join(out_dir, f"glue_opcodes_by_test.csv")
    )
    new_gas_df, poor_fit_dict = select_worst_case_estimates(
        results_df,
        params,
        group_by,
        anchor_rate,
        params_multipliers,
        glue_results_df,
        glue_opcodes_by_test,
    )
    new_gas_df.to_csv(os.path.join(out_dir, f"new_gas.csv"), index=False)
    worst_gas_df = compute_worst_gas_proposal(new_gas_df)
    # Add worst gas table to markdown report
    md_file.new_header(level=2, title="New gas proposal", add_table_of_contents="n")
    md_file.new_paragraph(
        "The following table shows the new gas cost for "
        "all operations and parameters with a good model fit."
    )
    md_file.new_paragraph("")
    table_data = ["Opcode", "Parameter", "Current Gas", "New Gas (Rounded)", "Change"]
    for _, row in worst_gas_df.iterrows():
        table_data.extend(
            [
                str(row["opcode"]),
                str(row["param"]),
                str(row["current_gas"]),
                str(int(row["new_gas_rounded"])),
                str(row["change"]),
            ]
        )
    md_file.new_table(
        columns=5, rows=len(worst_gas_df) + 1, text=table_data, text_align="center"
    )
    # Add section with gas cost comparison plot by client
    md_file.new_header(level=2, title="Gas costs by client", add_table_of_contents="n")
    md_file.new_paragraph(
        "The following plot shows the new gas costs (rounded) for each operation parameter "
        "across different clients, with error bars representing the confidence intervals."
    )
    md_file.new_paragraph("")
    create_and_save_new_gas_plot(new_gas_df, out_dir)
    md_file.new_line(
        md_file.new_inline_image(
            text="Gas costs by client", path="figs/gas_costs_by_client.png"
        )
    )
    # Table: worst runtime and glue adjustment per client and opcode/parameter
    md_file.new_paragraph(
        "The following table shows the worst-case runtime (after glue adjustment) "
        "and the glue adjustment applied for each opcode, parameter, and client."
    )
    md_file.new_paragraph("")
    detail_cols = ["opcode", "param", "client_name", "runtime_ms", "glue_adjustment", "new_gas_rounded"]
    if "glue_adjustment" not in new_gas_df.columns:
        new_gas_df["glue_adjustment"] = 0.0
    detail_df = (
        new_gas_df[detail_cols]
        .drop_duplicates()
        .sort_values(["opcode", "param", "client_name"])
    )
    detail_table_data = [
        "Opcode", "Parameter", "Client", "Runtime (ms)", "Glue Adj. (ms)", "New Gas (Rounded)"
    ]
    for _, row in detail_df.iterrows():
        detail_table_data.extend(
            [
                str(row["opcode"]),
                str(row["param"]),
                str(row["client_name"]),
                f"{row['runtime_ms']:.4f}",
                f"{row['glue_adjustment']:.4f}",
                str(int(row["new_gas_rounded"])),
            ]
        )
    md_file.new_table(
        columns=6,
        rows=len(detail_df) + 1,
        text=detail_table_data,
        text_align="center",
    )
    # Add table showing which test configurations were selected as worst case
    md_file.new_paragraph(
        "The following table shows which test configurations were selected as "
        "the worst case for each operation, parameter, and client."
    )
    md_file.new_paragraph("")
    config_cols = ["opcode", "param"] + group_by
    config_df = new_gas_df[config_cols].drop_duplicates().sort_values(config_cols)
    config_headers = ["Opcode", "Parameter"] + [
        col.replace("_", " ").title() for col in group_by
    ]
    config_table_data = config_headers.copy()
    for _, row in config_df.iterrows():
        config_table_data.extend([str(row[col]) for col in config_cols])
    md_file.new_table(
        columns=len(config_cols),
        rows=len(config_df) + 1,
        text=config_table_data,
        text_align="center",
    )
    # Add section on operations with bad fit
    md_file.new_header(level=2, title="Errors and caveats", add_table_of_contents="n")
    if len(poor_fit_dict) == 0:
        md_file.new_paragraph("All parameters had a good model fit.")
    else:
        md_file.new_paragraph("The following parameters had a poor model fit:")
        md_file.new_paragraph("")
        poor_fit_dict = dict(sorted(poor_fit_dict.items()))
        for (opcode, param), clients in poor_fit_dict.items():
            md_file.new_list([f"{opcode} - {param} - {', '.join(clients)}"])
    md_file.new_paragraph()
    # Add section on clients with missing estimations
    missing_clients_by_opcode = find_missing_client_estimations(
        results_df, target_operations
    )
    if len(missing_clients_by_opcode) == 0:
        md_file.new_paragraph("All operations have estimations for all clients.")
    else:
        md_file.new_paragraph(
            "The following operations have no estimation for the following clients:"
        )
        md_file.new_paragraph("")
        for opcode, clients in missing_clients_by_opcode.items():
            md_file.new_list([f"{opcode}: {', '.join(clients)}"])
    # Add section on glue opcodes with poor fit
    poor_fit_glue = find_poor_fit_glue_opcodes(
        glue_results_df, glue_opcodes_by_test, target_operations
    )
    md_file.new_paragraph()
    if len(poor_fit_glue) == 0:
        md_file.new_paragraph("All glue opcodes had a statistically significant fit.")
    else:
        md_file.new_paragraph(
            "The following glue opcodes had a poor fit (p-value >= 0.05), "
            "meaning their runtime could not be reliably estimated. "
            "The slope of the affected test opcodes is not adjusted for "
            "these glue opcodes' contribution:"
        )
        md_file.new_paragraph("")
        target_set = set(target_operations)
        for glue_opcode, info in poor_fit_glue.items():
            affected = sorted(
                op for op in info["test_opcodes"] if op in target_set
            )
            if not affected:
                continue
            md_file.new_list(
                [
                    f"**{glue_opcode}** (clients: {', '.join(info['clients'])}) "
                    f"— affects: {', '.join(affected)}"
                ]
            )
    # Finish and save markdown file
    md_file.create_md_file()


def generate_state_access_repricings_report(
    start_date: str,
    end_date: str,
    out_dir: str,
    anchor_rate: float,
    eip_number: int,
    group_by: List[str] = ["client_name", "test_name"],
) -> None:
    """Generate a gas proposal report for EIP-8038 state access parameters.

    Unlike generate_repricings_report (which reports per-opcode costs), this
    function maps model outputs to the named gas parameters used by multiple
    opcodes (GAS_WARM_ACCESS, GAS_COLD_STORAGE_ACCESS, etc.) and also computes
    the three derived parameters (GAS_STORAGE_CLEAR_REFUND,
    ACCESS_LIST_STORAGE_KEY_COST, ACCESS_LIST_ADDRESS_COST).
    """
    md_file = MdUtils(
        file_name=os.path.join(out_dir, "new_gas_proposal"),
        title=f"State access gas parameter proposal for EIP-{eip_number}",
    )
    md_file.new_paragraph(
        f"""
This is an automated report generated from the script `./src/estimate_{eip_number}_repricings.py`.
The runtime estimation results used as input can be found in
`./reports/eip-{eip_number}/{start_date}_{end_date}/runtime_estimation_autogenerated_report.md`.
"""
    )

    md_file.new_header(level=2, title="Methodology", add_table_of_contents="n")
    md_file.new_paragraph(
        f"""
New gas costs are calculated using an anchor rate of **{anchor_rate / 1e6:.0f} million gas per second**.
The formula used is:

```
new_gas = (anchor_rate * runtime_ms) / 1000
```

**Glue opcode adjustment:** Each benchmark test includes auxiliary "glue" opcodes that scale
linearly with the main opcode count. The regression slope captures the combined runtime of
both the target opcode and its glue opcodes, so we subtract the estimated glue opcode
runtime to isolate the true per-execution cost:

```
adjusted_slope = slope - sum(ratio_i * glue_runtime_i)
```

Only glue opcodes with a statistically significant fit (p-value < 0.05) are included.
The adjusted slope is clipped to a minimum of zero. The runtime estimation report for
glue opcode can be found [here](./glue_opcodes_autogenerated_report.md)

**Parameter mapping:** Each gas parameter is derived from one or more benchmark models
by selecting a specific regression coefficient (slope or `update`) after applying the
relevant filters (test name, cache strategy, account mode). For each parameter and client,
the worst-case value across all matching model configurations is used. The final proposal
takes the worst case across clients.

**Derived parameters** are computed from the directly estimated ones:

```
GAS_STORAGE_CLEAR_REFUND     = (GAS_COLD_STORAGE_WRITE + GAS_COLD_STORAGE_ACCESS) * (4800/5000)
ACCESS_LIST_STORAGE_KEY_COST = GAS_COLD_STORAGE_ACCESS
ACCESS_LIST_ADDRESS_COST     = GAS_COLD_ACCOUNT_CODE_ACCESS
```

For more information on how each test result is mapped to a parameter, check this
[estimation plan](../../estimation_plan.md).
"""
    )

    md_file.new_header(
        level=2, title="Understanding the results", add_table_of_contents="n"
    )
    md_file.new_paragraph(
        """
The table below shows the **worst-case** new gas cost across all tested clients for each
directly estimated parameter (taking the maximum across clients). This conservative approach
ensures the new gas costs account for the slowest implementation.

The **Change** column shows the relative change as a decimal (e.g., 1.0 = 100% increase,
-0.25 = 25% decrease).

For each parameter and client, the worst-case runtime across all matching test configurations
is selected. If any configuration has a statistically significant fit (p-value < 0.05), the
worst case among significant fits is used. Otherwise, the worst case from all configurations
is used. Parameters with no significant fits are listed in the "Errors and caveats" section.
"""
    )

    # Load data and compute gas parameters
    results_df = pd.read_csv(os.path.join(out_dir, "results.csv"))
    glue_results_df = pd.read_csv(os.path.join(out_dir, "glue_results.csv"))
    glue_opcodes_by_test = pd.read_csv(
        os.path.join(out_dir, "glue_opcodes_by_test.csv")
    )
    params_df, all_params_df, poor_fit_dict = compute_state_access_gas_params(
        results_df,
        anchor_rate,
        glue_results_df,
        glue_opcodes_by_test,
        group_by=group_by,
    )
    params_df.to_csv(os.path.join(out_dir, "new_gas.csv"), index=False)
    all_params_df.to_csv(os.path.join(out_dir, "new_gas_all_params.csv"), index=False)

    # Worst case across clients
    worst_direct = (
        params_df.groupby("gas_param")["new_gas_rounded"]
        .max()
        .reset_index()
        .sort_values("gas_param")
    )
    worst_direct["current_gas"] = worst_direct["gas_param"].map(
        _STATE_ACCESS_CURRENT_GAS
    )
    worst_direct["change"] = (
        worst_direct["new_gas_rounded"] / worst_direct["current_gas"] - 1
    ).round(2)

    # Directly estimated parameters table
    md_file.new_header(
        level=2, title="Directly estimated parameters", add_table_of_contents="n"
    )
    md_file.new_paragraph(
        "The following table shows new gas costs for directly estimated parameters."
    )
    md_file.new_paragraph("")
    table_data = ["Parameter", "Current Gas", "New Gas (Rounded)", "Change"]
    for _, row in worst_direct.iterrows():
        table_data.extend(
            [
                str(row["gas_param"]),
                str(int(row["current_gas"])) if pd.notna(row["current_gas"]) else "N/A",
                str(int(row["new_gas_rounded"])),
                str(row["change"]),
            ]
        )
    md_file.new_table(
        columns=4, rows=len(worst_direct) + 1, text=table_data, text_align="center"
    )

    # Derived parameters table
    cold_storage_access = worst_direct.get("GAS_COLD_STORAGE_ACCESS", 0)
    cold_storage_write = worst_direct.get("GAS_COLD_STORAGE_WRITE", 0)
    cold_account_code_access = worst_direct.get("GAS_COLD_ACCOUNT_CODE_ACCESS", 0)
    derived = {
        "GAS_STORAGE_CLEAR_REFUND": int(
            np.ceil((cold_storage_write + cold_storage_access) * (4800 / 5000))
        ),
        "ACCESS_LIST_STORAGE_KEY_COST": int(cold_storage_access),
        "ACCESS_LIST_ADDRESS_COST": int(cold_account_code_access),
    }
    derived_df = pd.DataFrame(
        [{"gas_param": k, "new_gas_rounded": v} for k, v in derived.items()]
    )
    if not derived_df.empty:
        md_file.new_header(
            level=2, title="Derived parameters", add_table_of_contents="n"
        )
        md_file.new_paragraph(
            "The following parameters are computed from the directly estimated ones."
        )
        md_file.new_paragraph("")
        derived_df["current_gas"] = derived_df["gas_param"].map(
            _STATE_ACCESS_CURRENT_GAS
        )
        derived_df["change"] = (
            derived_df["new_gas_rounded"] / derived_df["current_gas"] - 1
        ).round(2)
        derived_table_data = ["Parameter", "Current Gas", "New Gas (Rounded)", "Change"]
        for _, row in derived_df.iterrows():
            derived_table_data.extend(
                [
                    str(row["gas_param"]),
                    (
                        str(int(row["current_gas"]))
                        if pd.notna(row["current_gas"])
                        else "N/A"
                    ),
                    str(int(row["new_gas_rounded"])),
                    str(row["change"]),
                ]
            )
        md_file.new_table(
            columns=4,
            rows=len(derived_df) + 1,
            text=derived_table_data,
            text_align="center",
        )

    # Gas costs by client plot
    if not params_df.empty:
        md_file.new_header(
            level=2, title="Gas costs by client", add_table_of_contents="n"
        )
        md_file.new_paragraph(
            "The following plot shows new gas costs (rounded) for each parameter "
            "across different clients, with error bars representing the confidence intervals."
        )
        md_file.new_paragraph("")
        create_and_save_state_access_gas_plot(params_df, out_dir)
        md_file.new_line(
            md_file.new_inline_image(
                text="State access gas parameters by client",
                path="figs/state_access_gas_params_by_client.png",
            )
        )
        # Table: worst runtime and glue adjustment per client and parameter
        md_file.new_paragraph(
            "The following table shows the worst-case runtime (after glue adjustment) "
            "and the glue adjustment applied for each parameter and client."
        )
        md_file.new_paragraph("")
        detail_cols = ["gas_param", "client_name", "runtime_ms", "glue_adjustment", "new_gas_rounded"]
        detail_df = (
            params_df[detail_cols]
            .drop_duplicates()
            .sort_values(["gas_param", "client_name"])
        )
        detail_table_data = [
            "Parameter", "Client", "Runtime (ms)", "Glue Adj. (ms)", "New Gas (Rounded)"
        ]
        for _, row in detail_df.iterrows():
            detail_table_data.extend(
                [
                    str(row["gas_param"]),
                    str(row["client_name"]),
                    f"{row['runtime_ms']:.4f}",
                    f"{row['glue_adjustment']:.4f}",
                    str(int(row["new_gas_rounded"])),
                ]
            )
        md_file.new_table(
            columns=5,
            rows=len(detail_df) + 1,
            text=detail_table_data,
            text_align="center",
        )

    # Table showing which test/opcode was selected for each (gas_param, client)
    md_file.new_header(
        level=2, title="Selected configurations", add_table_of_contents="n"
    )
    md_file.new_paragraph(
        "The following table shows which test configuration was selected as the "
        "worst case for each parameter and client."
    )
    md_file.new_paragraph("")
    extra_group_by_cols = [
        f"selected_{col}"
        for col in group_by
        if col not in ("client_name", "test_name") and f"selected_{col}" in params_df.columns
    ]
    config_cols = [
        "gas_param",
        "client_name",
        "selected_test",
        "selected_opcode",
        "selected_coef",
    ] + extra_group_by_cols
    config_df = (
        params_df[config_cols]
        .drop_duplicates()
        .sort_values(["gas_param", "client_name"])
    )
    config_headers = ["Parameter", "Client", "Test", "Opcode", "Coefficient"] + [
        col.replace("selected_", "").replace("_", " ").title()
        for col in extra_group_by_cols
    ]
    config_table_data = config_headers.copy()
    for _, row in config_df.iterrows():
        config_table_data.extend([str(row[col]) for col in config_cols])
    md_file.new_table(
        columns=len(config_cols),
        rows=len(config_df) + 1,
        text=config_table_data,
        text_align="center",
    )

    # Errors and caveats
    md_file.new_header(level=2, title="Errors and caveats", add_table_of_contents="n")
    if poor_fit_dict:
        md_file.new_paragraph(
            "The following parameters had no statistically significant model fit:"
        )
        md_file.new_paragraph("")
        for gas_param, clients in sorted(poor_fit_dict.items()):
            md_file.new_list([f"{gas_param} — {', '.join(sorted(clients))}"])
    else:
        md_file.new_paragraph("All parameters had a good model fit.")
    md_file.new_paragraph()

    # Missing clients per parameter
    present_by_param = (
        params_df.groupby("gas_param")["client_name"].apply(set).to_dict()
    )
    all_clients = {"geth", "reth", "nethermind", "besu", "erigon"}
    missing_by_param = {
        gp: sorted(all_clients - clients)
        for gp, clients in present_by_param.items()
        if all_clients - clients
    }
    # Also flag parameters with no data at all
    for gp in _STATE_ACCESS_PARAM_SOURCES:
        if gp not in present_by_param:
            missing_by_param[gp] = sorted(all_clients)
    if missing_by_param:
        md_file.new_paragraph(
            "The following parameters have no estimation for the following clients:"
        )
        md_file.new_paragraph("")
        for gas_param, clients in sorted(missing_by_param.items()):
            md_file.new_list([f"{gas_param}: {', '.join(clients)}"])
    else:
        md_file.new_paragraph("All parameters have estimations for all clients.")

    # Poor fit glue opcodes
    poor_fit_glue = find_poor_fit_glue_opcodes(glue_results_df, glue_opcodes_by_test)
    md_file.new_paragraph()
    if poor_fit_glue:
        # Map glue opcodes to affected gas parameters via test_names
        # Build test_name -> set of gas_params mapping
        test_name_to_params: Dict[str, Set[str]] = {}
        for gas_param, sources in _STATE_ACCESS_PARAM_SOURCES.items():
            for filter_dict, _ in sources:
                tn = filter_dict.get("test_name")
                if tn:
                    test_name_to_params.setdefault(tn, set()).add(gas_param)
        # For each glue opcode, find which test_names it appears in,
        # then map to gas parameters
        glue_to_params: Dict[str, Set[str]] = {}
        for glue_opcode in poor_fit_glue:
            affected_test_names = glue_opcodes_by_test.loc[
                glue_opcodes_by_test["glue_opcode"] == glue_opcode, "test_name"
            ].unique()
            affected_params = set()
            for tn in affected_test_names:
                affected_params.update(test_name_to_params.get(tn, set()))
            if affected_params:
                glue_to_params[glue_opcode] = affected_params

        if glue_to_params:
            md_file.new_paragraph(
                "The following glue opcodes had a poor fit (p-value >= 0.05), "
                "meaning their runtime could not be reliably estimated. "
                "The slope of the affected parameters is not adjusted for "
                "these glue opcodes' contribution:"
            )
            md_file.new_paragraph("")
            for glue_opcode in sorted(glue_to_params):
                info = poor_fit_glue[glue_opcode]
                params = sorted(glue_to_params[glue_opcode])
                md_file.new_list(
                    [
                        f"**{glue_opcode}** (clients: {', '.join(info['clients'])}) "
                        f"— affects: {', '.join(params)}"
                    ]
                )
        else:
            md_file.new_paragraph(
                "Some glue opcodes had a poor fit but they do not affect any "
                "gas parameters."
            )
    else:
        md_file.new_paragraph("All glue opcodes had a statistically significant fit.")

    md_file.create_md_file()
