import os
import sys
import numpy as np
import warnings
import pandas as pd
from tqdm import tqdm
from typing import Dict, List
from pathlib import Path
from mdutils.mdutils import MdUtils

# Suppress warnings
warnings.filterwarnings("ignore", module="statsmodels")
warnings.filterwarnings("ignore", message="Tight layout not applied")
pd.options.mode.chained_assignment = None


sys.path.append(str(Path(__file__).parent))
from plotting import create_and_save_new_gas_plot
from data import get_current_gas_cost
from runtime_estimation import (
    estimate_run_time_for_simple_operation,
    estimate_run_time_for_non_simple_operation,
)
from plotting import create_and_save_new_gas_plot


def generate_runtime_report(
    start_date: str,
    end_date: str,
    eip_number: int,
    gas_bench_df: pd.DataFrame,
    out_dir: str,
    params: List[str],
    simple_operations: List[str] = [],
    variable_operations: List[str] = [],
    file_name_ending: str = "",
) -> None:
    # Start markdown report
    md_file = MdUtils(
        file_name=os.path.join(
            out_dir, f"runtime_estimation_autogenerated_report" + file_name_ending
        ),
        title=f"Operation run times estimation results - EIP-{eip_number}",
    )
    md_file.new_header(level=1, title="Introduction", add_table_of_contents="n")
    md_file.new_paragraph(
        f"""
This is an automated report generated from the opcode run times
estimation script `./src/estimate_{eip_number}_repricings.py`. The script
uses data generated by running the
[EEST benchmark suite](https://github.com/ethereum/execution-spec-tests/tree/main/tests/benchmark)
with the [Nethermind benchmarking tooling](https://github.com/NethermindEth/gas-benchmarks).

The data includes all the tests for operations repriced in EIP-{eip_number} run
between {start_date} and {end_date}.

For each operation and client, an NNLS linear regression model is fitted to estimate the
operation run time as a function of the operation count and other operation-specific parameters.
The results are presented below.
"""
    )

    md_file.new_header(
        level=1, title="How to Interpret the Results", add_table_of_contents="n"
    )

    md_file.new_header(level=2, title="Model Used", add_table_of_contents="n")
    md_file.new_paragraph(
        """
**Non-Negative Least Squares (NNLS) Linear Regression** is used to estimate operation runtimes.
This model ensures all coefficients are non-negative, which is physically meaningful since
execution time cannot be negative. The model estimates runtime as a linear combination of:

- **Constant term (intercept)**: Base overhead for executing the test, which includes setup and teardown time
- **Operation count (slope)**: Number of times the operation is executed in the test. This paramater 
is the one that allows us to estimate the per-operation runtime.
- **Operation-specific parameters**: Variables like number of rounds, message size, or number of pairs

For simple operations, the model estimates: `runtime = intercept + slope × operation_count`

For variable operations, the model estimates: `runtime = intercept + slope × operation_count +
 param1_coef × operation_count × param1 + param2_coef × operation_count × param2 + ...`
"""
    )

    md_file.new_header(
        level=2, title="Model Quality Metrics", add_table_of_contents="n"
    )
    md_file.new_paragraph(
        """
Each model reports two key metrics to assess the quality of the fit:

**R² (R-squared / Coefficient of Determination)**
- Ranges from 0 to 1 (or can be negative for very poor fits)
- Measures how well the model explains the variance in the data
- **Interpretation**:
  - R² > 0.9: Excellent fit - the model explains >90% of the variance
  - R² > 0.7: Good fit - the model captures most of the relationship
  - R² > 0.5: Acceptable fit - the model has predictive power but notable variance remains
  - R² < 0.5: Poor fit - the model may not be reliable

**p-value**
- Tests the statistical significance of each coefficient, based on a bootstrap sample estimation
- **Interpretation**:
  - p < 0.05: Statistically significant - the parameter has a real effect on runtime
  - p ≥ 0.05: Not significant - the parameter's effect cannot be distinguished from random noise

We also plot some diagnostic graphs for each operation and client combination to visually assess the model fit.
"""
    )

    # Estimate run times for simple operations
    out_list = []
    if len(simple_operations) > 0:
        for op in tqdm(simple_operations, desc=f"Estimating simple operations"):
            # Run estimation and add to report
            op_list = estimate_run_time_for_simple_operation(
                gas_bench_df, op, md_file, out_dir
            )
            out_list.extend(op_list)
    # Estimate run times for variable operations
    if len(variable_operations) > 0:
        for op in tqdm(variable_operations, desc=f"Estimating variable operations"):
            # Run estimation and add to report
            opcode_list = estimate_run_time_for_non_simple_operation(
                gas_bench_df, op, md_file, out_dir, params
            )
            out_list.extend(opcode_list)
    # Create and save output dataframe
    out_df = pd.DataFrame(out_list)
    out_df.to_csv(os.path.join(out_dir, f"results{file_name_ending}.csv"), index=False)
    # Finish and save markdown file
    md_file.new_table_of_contents(depth=1)
    md_file.create_md_file()


def generate_repricings_report(
    start_date: str,
    end_date: str,
    out_dir: str,
    anchor_rate: float,
    eip_number: int,
    params: List[str],
    params_multipliers: Dict[str, float],
    file_name_ending: str = "",
) -> None:
    # Start markdown report
    md_file = MdUtils(
        file_name=os.path.join(out_dir, f"new_gas_proposal" + file_name_ending),
        title=f"New gas cost proposal for EIP-{eip_number}",
    )
    md_file.new_paragraph(
        f"""
This is an automated report generated from the script `./src/estimate_{eip_number}_repricings.py`. 
The script uses the runtime estimation output generated by this script. 
The report with the runtime estimation results can be found in 
`./reports/eip-{eip_number}/{start_date}_{end_date}/runtime_estimation_autogenerated_report{file_name_ending}.md`.
"""
    )
    md_file.new_header(level=2, title="Methodology", add_table_of_contents="n")
    md_file.new_paragraph(
        f"""
New gas costs are calculated using an anchor rate of **{anchor_rate / 1e6:.0f} million gas per second**,
which represents a target execution rate for EVM operations. The formula used is:

```
new_gas = (anchor_rate * runtime_ms) / 1000
```

Where `runtime_ms` is the estimated runtime in milliseconds from the regression models.
"""
    )
    md_file.new_header(
        level=2, title="Understanding the results", add_table_of_contents="n"
    )
    md_file.new_paragraph(
        """
The table below shows the **worst-case** gas costs across all tested clients (taking the maximum
estimated cost per operation). This conservative approach ensures that the new gas costs account
for the slowest implementation among the major Ethereum clients.

The **Change** column shows the relative change as a decimal (e.g., 1.0 = 100% increase, 0.5 = 50% increase,
-0.25 = 25% decrease). Operations with `inf` indicate costs going from 0 to a positive value.

Only operations and parameters with good model fits (R² > 0.5 and p-value < 0.05) are included
in the gas cost proposals. Operations with poor model fits are listed separately in the
"Errors and caveats" section.
"""
    )
    # Load estimation results
    results_df = pd.read_csv(os.path.join(out_dir, f"results{file_name_ending}.csv"))
    # Process estimation results and compute new gas costs
    all_params = ["slope"] + params
    new_gas_df = pd.DataFrame()
    poor_fit_dict = dict()
    for param in all_params:
        # Good fits
        param_df = results_df[
            (results_df[param + "_pvalue"] < 0.05) & (results_df["rsquared"] > 0.5)
        ][
            [
                "opcode",
                "client",
                param,
                param + "_conf_int_low",
                param + "_conf_int_high",
            ]
        ]
        param_df = param_df.rename(
            columns={
                param: "runtime_ms",
                param + "_conf_int_low": "conf_int_low",
                param + "_conf_int_high": "conf_int_high",
            }
        )
        if param in params_multipliers:
            multiplier = params_multipliers[param]
        else:
            multiplier = 1.0
        param_df["new_gas"] = (anchor_rate * param_df["runtime_ms"] * multiplier) / 1e3
        param_df["new_gas_rounded"] = np.ceil(param_df["new_gas"])
        param_df["new_gas_conf_int_low"] = np.ceil(
            (anchor_rate * param_df["conf_int_low"]) / 1e3
        )
        param_df["new_gas_conf_int_high"] = np.ceil(
            (anchor_rate * param_df["conf_int_high"]) / 1e3
        )
        param_df["param"] = np.where(param == "slope", "constant", param)
        new_gas_df = pd.concat([new_gas_df, param_df], ignore_index=True)
        # Poor fits
        poor_fit_df = results_df[
            (results_df[param + "_pvalue"] >= 0.05) | (results_df["rsquared"] <= 0.5)
        ][["opcode", "client"]].dropna()
        for row in poor_fit_df.itertuples():
            if (row.opcode, param) not in poor_fit_dict:
                poor_fit_dict[(row.opcode, param)] = set([row.client])
            else:
                poor_fit_dict[(row.opcode, param)] = poor_fit_dict[
                    (row.opcode, param)
                ].union(set([row.client]))
    # Save cost estimation
    new_gas_df.to_csv(
        os.path.join(out_dir, f"new_gas{file_name_ending}.csv"), index=False
    )
    # Get worse per client
    worst_gas_df = (
        new_gas_df.groupby(["opcode", "param"])["new_gas_rounded"]
        .max()
        .reset_index()
        .sort_index()
    )
    # Add current gas costs
    worst_gas_df["current_gas"] = worst_gas_df.apply(
        lambda row: get_current_gas_cost(row["opcode"], row["param"]), axis=1
    )
    # Calculate increase
    worst_gas_df["change"] = (
        worst_gas_df["new_gas_rounded"] / worst_gas_df["current_gas"] - 1
    )
    worst_gas_df["change"] = worst_gas_df["change"].round(2)
    # Add worst gas table to markdown report
    md_file.new_header(level=2, title="New gas proposal", add_table_of_contents="n")
    md_file.new_paragraph(
        "The following table shows the new gas cost for "
        "all operations and parameters with a good model fit."
    )
    md_file.new_paragraph("")
    table_data = ["Opcode", "Parameter", "Current Gas", "New Gas (Rounded)", "Change"]
    for _, row in worst_gas_df.iterrows():
        table_data.extend(
            [
                str(row["opcode"]),
                str(row["param"]),
                str(row["current_gas"]),
                str(int(row["new_gas_rounded"])),
                str(row["change"]),
            ]
        )
    md_file.new_table(
        columns=5, rows=len(worst_gas_df) + 1, text=table_data, text_align="center"
    )
    # Add section with gas cost comparison plot by client
    md_file.new_header(level=2, title="Gas costs by client", add_table_of_contents="n")
    md_file.new_paragraph(
        "The following plot shows the new gas costs (rounded) for each operation parameter "
        "across different clients, with error bars representing the confidence intervals."
    )
    md_file.new_paragraph("")
    create_and_save_new_gas_plot(new_gas_df, out_dir)
    md_file.new_line(
        md_file.new_inline_image(
            text="Gas costs by client", path="figs/gas_costs_by_client.png"
        )
    )
    # Add section on operations with bad fit
    md_file.new_header(level=2, title="Errors and caveats", add_table_of_contents="n")
    if len(poor_fit_dict) == 0:
        md_file.new_paragraph("All parameters had a good model fit.")
    else:
        md_file.new_paragraph("The following parameters had a poor model fit:")
        md_file.new_paragraph("")
        poor_fit_dict = dict(sorted(poor_fit_dict.items()))
        for (opcode, param), clients in poor_fit_dict.items():
            md_file.new_list([f"{opcode} - {param} - {', '.join(clients)}"])
    md_file.new_paragraph()
    # Add section on clients with missing estimations
    estimation_by_client = results_df.groupby("opcode")["client"].nunique()
    all_clients = set({"geth", "reth", "nethermind", "besu", "erigon"})
    opcodes_with_missing_clients = estimation_by_client[estimation_by_client < 5].index
    missing_clients_by_opcode = {}
    for opcode in opcodes_with_missing_clients:
        present_clients = set(
            results_df[results_df["opcode"] == opcode]["client"].unique()
        )
        missing_clients = all_clients - present_clients
        missing_clients_by_opcode[opcode] = sorted(missing_clients)
    if len(missing_clients_by_opcode) == 0:
        md_file.new_paragraph("All operations have estimations for all clients.")
    else:
        md_file.new_paragraph(
            "The following operations have no estimation for the following clients:"
        )
        md_file.new_paragraph("")
        for opcode, clients in missing_clients_by_opcode.items():
            md_file.new_list([f"{opcode}: {', '.join(clients)}"])
    # Finish and save markdown file
    md_file.create_md_file()
