import os
import sys
import warnings
import pandas as pd
from tqdm import tqdm
from typing import Dict, List
from pathlib import Path
from mdutils.mdutils import MdUtils

# Suppress warnings
warnings.filterwarnings("ignore", module="statsmodels")
warnings.filterwarnings("ignore", message="Tight layout not applied")
pd.options.mode.chained_assignment = None


sys.path.append(str(Path(__file__).parent))
from plotting import create_and_save_new_gas_plot
from runtime_estimation import (
    estimate_run_time_for_simple_operation,
    estimate_run_time_for_non_simple_operation,
)
from proposal import (
    select_worst_case_estimates,
    compute_worst_gas_proposal,
    find_missing_client_estimations,
    find_poor_fit_glue_opcodes,
)


def generate_runtime_report(
    start_date: str,
    end_date: str,
    eip_number: int,
    gas_bench_df: pd.DataFrame,
    out_dir: str,
    params: List[str],
    simple_operations: List[str] = [],
    variable_operations: List[str] = [],
    query_source: str = "gas_bench",
    group_by: List[str] = ["client_name", "test_name"],
) -> None:
    # Start markdown report
    md_file = MdUtils(
        file_name=os.path.join(out_dir, f"runtime_estimation_autogenerated_report"),
        title=f"Operation run times estimation results - EIP-{eip_number}",
    )
    md_file.new_header(level=1, title="Introduction", add_table_of_contents="n")
    if query_source == "gas_bench":
        md_file.new_paragraph(
            f"""
This is an automated report generated from the opcode run times
estimation script `./src/estimate_{eip_number}_repricings.py`. The script
uses data generated by running the
[EEST benchmark suite](https://github.com/ethereum/execution-spec-tests/tree/main/tests/benchmark)
with the [Nethermind benchmarking tooling](https://github.com/NethermindEth/gas-benchmarks).
"""
        )
    else:  # benchmarkoor
        md_file.new_paragraph(
            f"""
This is an automated report generated from the opcode run times
estimation script `./src/estimate_{eip_number}_repricings.py`. The script
uses data generated by running the
[EEST benchmark suite](https://github.com/ethereum/execution-spec-tests/tree/main/tests/benchmark)
with the [Benchmarkoor](https://github.com/ethpandaops/benchmarkoor) tool from EthPandasOps.
""")
    md_file.new_paragraph(
            f"""
The data includes all the tests for operations repriced in EIP-{eip_number} run
between {start_date} and {end_date}.

For each operation and client, an NNLS linear regression model is fitted to estimate the
operation run time as a function of the operation count and other operation-specific parameters.
The results are presented below.
"""
    )
    md_file.new_header(
        level=1, title="How to Interpret the Results", add_table_of_contents="n"
    )

    md_file.new_header(level=2, title="Model Used", add_table_of_contents="n")
    md_file.new_paragraph(
        """
**Non-Negative Least Squares (NNLS) Linear Regression** is used to estimate operation runtimes.
This model ensures all coefficients are non-negative, which is physically meaningful since
execution time cannot be negative. The model estimates runtime as a linear combination of:

- **Constant term (intercept)**: Base overhead for executing the test, which includes setup and teardown time
- **Operation count (slope)**: Number of times the operation is executed in the test. This paramater 
is the one that allows us to estimate the per-operation runtime.
- **Operation-specific parameters**: Variables like number of rounds, message size, or number of pairs

For simple operations, the model estimates: `runtime = intercept + slope × operation_count`

For variable operations, the model estimates: `runtime = intercept + slope × operation_count +
 param1_coef × operation_count × param1 + param2_coef × operation_count × param2 + ...`
"""
    )

    md_file.new_header(
        level=2, title="Model Quality Metrics", add_table_of_contents="n"
    )
    md_file.new_paragraph(
        """
Each model reports two key metrics to assess the quality of the fit:

**R² (R-squared / Coefficient of Determination)**
- Ranges from 0 to 1 (or can be negative for very poor fits)
- Measures how well the model explains the variance in the data
- **Interpretation**:
  - R² > 0.9: Excellent fit - the model explains >90% of the variance
  - R² > 0.7: Good fit - the model captures most of the relationship
  - R² > 0.5: Acceptable fit - the model has predictive power but notable variance remains
  - R² < 0.5: Poor fit - the model may not be reliable

**p-value**
- Tests the statistical significance of each coefficient, based on a bootstrap sample estimation
- **Interpretation**:
  - p < 0.05: Statistically significant - the parameter has a real effect on runtime
  - p ≥ 0.05: Not significant - the parameter's effect cannot be distinguished from random noise

We also plot some diagnostic graphs for each operation and client combination to visually assess the model fit.
"""
    )

    # Estimate run times for simple operations
    out_list = []
    if len(simple_operations) > 0:
        for op in tqdm(simple_operations, desc=f"Estimating simple operations"):
            # Run estimation and add to report
            op_list = estimate_run_time_for_simple_operation(
                gas_bench_df, op, md_file, out_dir, group_by=group_by
            )
            out_list.extend(op_list)
    # Estimate run times for variable operations
    if len(variable_operations) > 0:
        for op in tqdm(variable_operations, desc=f"Estimating variable operations"):
            # Run estimation and add to report
            opcode_list = estimate_run_time_for_non_simple_operation(
                gas_bench_df, op, md_file, out_dir, params, group_by=group_by
            )
            out_list.extend(opcode_list)
    # Create and save output dataframe
    out_df = pd.DataFrame(out_list)
    out_df.to_csv(os.path.join(out_dir, f"results.csv"), index=False)
    # Finish and save markdown file
    md_file.new_table_of_contents(depth=1)
    md_file.create_md_file()


def generate_repricings_report(
    start_date: str,
    end_date: str,
    out_dir: str,
    anchor_rate: float,
    eip_number: int,
    params: List[str],
    params_multipliers: Dict[str, float],
    target_operations: List[str],
    group_by: List[str] = ["client_name", "test_name"],
) -> None:
    # Start markdown report
    md_file = MdUtils(
        file_name=os.path.join(out_dir, f"new_gas_proposal"),
        title=f"New gas cost proposal for EIP-{eip_number}",
    )
    md_file.new_paragraph(
        f"""
This is an automated report generated from the script `./src/estimate_{eip_number}_repricings.py`. 
The script uses the runtime estimation output generated by this script. 
The report with the runtime estimation results can be found in 
`./reports/eip-{eip_number}/{start_date}_{end_date}/runtime_estimation_autogenerated_report.md`.
"""
    )
    md_file.new_header(level=2, title="Methodology", add_table_of_contents="n")
    md_file.new_paragraph(
        f"""
New gas costs are calculated using an anchor rate of **{anchor_rate / 1e6:.0f} million gas per second**,
which represents a target execution rate for EVM operations. The formula used is:

```
new_gas = (anchor_rate * runtime_ms) / 1000
```

Where `runtime_ms` is the estimated runtime in milliseconds from the regression models.

**Glue opcode adjustment:** Each benchmark test includes auxiliary "glue" opcodes (e.g., PUSH, CALL)
that scale linearly with the main opcode count. Because the regression model's slope coefficient
captures the combined runtime of both the target opcode and its glue opcodes, we subtract the
estimated glue opcode runtime to isolate the true per-execution cost of the target opcode:

```
adjusted_slope = slope - sum(ratio_i * glue_runtime_i)
```

Where `ratio_i` is the average number of executions of glue opcode *i* per execution of the target
opcode (averaged across test parameters), and `glue_runtime_i` is the estimated per-execution runtime
of glue opcode *i* for the given client. Only glue opcodes with a statistically significant fit
(p-value < 0.05) are included in the adjustment. The adjusted slope is clipped to a minimum of zero.
Glue opcode runtimes are estimated separately using the same NNLS regression approach (see the
glue opcodes report for details).
"""
    )
    md_file.new_header(
        level=2, title="Understanding the results", add_table_of_contents="n"
    )
    md_file.new_paragraph(
        """
The table below shows the **worst-case** gas costs across all tested clients (taking the maximum
estimated cost per operation). This conservative approach ensures that the new gas costs account
for the slowest implementation among the major Ethereum clients.

The **Change** column shows the relative change as a decimal (e.g., 1.0 = 100% increase, 0.5 = 50% increase,
-0.25 = 25% decrease). Operations with `inf` indicate costs going from 0 to a positive value.

For each operation, parameter, and client combination, the worst-case runtime across all
test configurations is selected. If any configuration has a statistically significant fit
(p-value < 0.05), the worst case among significant fits is used. Otherwise, the worst case
from all configurations is used. Operations with no significant fits are listed separately
in the "Errors and caveats" section.
"""
    )
    # Load estimation results and compute new gas costs
    results_df = pd.read_csv(os.path.join(out_dir, f"results.csv"))
    glue_results_df = pd.read_csv(os.path.join(out_dir, f"glue_results.csv"))
    glue_opcodes_by_test = pd.read_csv(os.path.join(out_dir, f"glue_opcodes_by_test.csv"))
    new_gas_df, poor_fit_dict = select_worst_case_estimates(
        results_df,
        params,
        group_by,
        anchor_rate,
        params_multipliers,
        glue_results_df,
        glue_opcodes_by_test,
    )
    new_gas_df.to_csv(os.path.join(out_dir, f"new_gas.csv"), index=False)
    worst_gas_df = compute_worst_gas_proposal(new_gas_df)
    # Add worst gas table to markdown report
    md_file.new_header(level=2, title="New gas proposal", add_table_of_contents="n")
    md_file.new_paragraph(
        "The following table shows the new gas cost for "
        "all operations and parameters with a good model fit."
    )
    md_file.new_paragraph("")
    table_data = ["Opcode", "Parameter", "Current Gas", "New Gas (Rounded)", "Change"]
    for _, row in worst_gas_df.iterrows():
        table_data.extend(
            [
                str(row["opcode"]),
                str(row["param"]),
                str(row["current_gas"]),
                str(int(row["new_gas_rounded"])),
                str(row["change"]),
            ]
        )
    md_file.new_table(
        columns=5, rows=len(worst_gas_df) + 1, text=table_data, text_align="center"
    )
    # Add section with gas cost comparison plot by client
    md_file.new_header(level=2, title="Gas costs by client", add_table_of_contents="n")
    md_file.new_paragraph(
        "The following plot shows the new gas costs (rounded) for each operation parameter "
        "across different clients, with error bars representing the confidence intervals."
    )
    md_file.new_paragraph("")
    create_and_save_new_gas_plot(new_gas_df, out_dir)
    md_file.new_line(
        md_file.new_inline_image(
            text="Gas costs by client", path="figs/gas_costs_by_client.png"
        )
    )
    # Add table showing which test configurations were selected as worst case
    md_file.new_paragraph(
        "The following table shows which test configurations were selected as "
        "the worst case for each operation, parameter, and client."
    )
    md_file.new_paragraph("")
    config_cols = ["opcode", "param"] + group_by
    config_df = new_gas_df[config_cols].drop_duplicates().sort_values(config_cols)
    config_headers = ["Opcode", "Parameter"] + [
        col.replace("_", " ").title() for col in group_by
    ]
    config_table_data = config_headers.copy()
    for _, row in config_df.iterrows():
        config_table_data.extend([str(row[col]) for col in config_cols])
    md_file.new_table(
        columns=len(config_cols),
        rows=len(config_df) + 1,
        text=config_table_data,
        text_align="center",
    )
    # Add section on operations with bad fit
    md_file.new_header(level=2, title="Errors and caveats", add_table_of_contents="n")
    if len(poor_fit_dict) == 0:
        md_file.new_paragraph("All parameters had a good model fit.")
    else:
        md_file.new_paragraph("The following parameters had a poor model fit:")
        md_file.new_paragraph("")
        poor_fit_dict = dict(sorted(poor_fit_dict.items()))
        for (opcode, param), clients in poor_fit_dict.items():
            md_file.new_list([f"{opcode} - {param} - {', '.join(clients)}"])
    md_file.new_paragraph()
    # Add section on clients with missing estimations
    missing_clients_by_opcode = find_missing_client_estimations(results_df, target_operations)
    if len(missing_clients_by_opcode) == 0:
        md_file.new_paragraph("All operations have estimations for all clients.")
    else:
        md_file.new_paragraph(
            "The following operations have no estimation for the following clients:"
        )
        md_file.new_paragraph("")
        for opcode, clients in missing_clients_by_opcode.items():
            md_file.new_list([f"{opcode}: {', '.join(clients)}"])
    # Add section on glue opcodes with poor fit
    poor_fit_glue = find_poor_fit_glue_opcodes(glue_results_df, glue_opcodes_by_test, target_operations)
    md_file.new_paragraph()
    if len(poor_fit_glue) == 0:
        md_file.new_paragraph(
            "All glue opcodes had a statistically significant fit."
        )
    else:
        md_file.new_paragraph(
            "The following glue opcodes had a poor fit (p-value >= 0.05), "
            "meaning their runtime could not be reliably estimated. "
            "The slope of the affected test opcodes is not adjusted for "
            "these glue opcodes' contribution:"
        )
        md_file.new_paragraph("")
        for glue_opcode, info in poor_fit_glue.items():
            md_file.new_list(
                [
                    f"**{glue_opcode}** (clients: {', '.join(info['clients'])}) "
                    f"— affects: {', '.join(info['test_opcodes'])}"
                ]
            )
    # Finish and save markdown file
    md_file.create_md_file()
